### ISSUE TITLE
Confidentiality Issue From MAQ Software's.

### ISSUE THREAD

**Issue by rajnish-488** [pragyagautam02/Power-BI-Automation#4]
The is not the secure place to se the code which belong to MAQ Software.
so we request you to pleased not store the file of MAQ software away from the on-premise computer of the MAQ.

Thank you
Rajnish Singh
Senior Intern(2 weeks)
MAQ Softwares.

**Comment by pragyagautam02** [comment]
sab chalta hai

Senior Software Engineer (9 year)

**Comment by rajnish-488** [comment]
sorry pragya ya message akask ko bhaj raha tha path pa dyan nahi diya tumhe aa gaya

**Comment by pragyagautam02** [comment]
areee, ye replies bhi akash hi kr rha h mere desktop se. But by god tmne toh darra hi diya tha :(
